--
-- PostgreSQL database dump
--

-- Dumped from database version 15.0
-- Dumped by pg_dump version 15.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: dlk_informacional; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA dlk_informacional;


ALTER SCHEMA dlk_informacional OWNER TO postgres;

--
-- Name: dlk_torrecontrol; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA dlk_torrecontrol;


ALTER SCHEMA dlk_torrecontrol OWNER TO postgres;

--
-- Name: dmt_torrecontrol; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA dmt_torrecontrol;


ALTER SCHEMA dmt_torrecontrol OWNER TO postgres;

--
-- Name: dwh_torrecontrol; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA dwh_torrecontrol;


ALTER SCHEMA dwh_torrecontrol OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Dlk_cat_acc_claim_empleados; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."Dlk_cat_acc_claim_empleados" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_claim_empleados" OWNER TO postgres;

--
-- Name: Dlk_cat_acc_claim_empleados_Id_seq; Type: SEQUENCE; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_claim_empleados" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dlk_torrecontrol."Dlk_cat_acc_claim_empleados_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Dlk_cat_acc_claim_roles; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."Dlk_cat_acc_claim_roles" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_claim_roles" OWNER TO postgres;

--
-- Name: Dlk_cat_acc_claim_roles_Id_seq; Type: SEQUENCE; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_claim_roles" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dlk_torrecontrol."Dlk_cat_acc_claim_roles_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Dlk_cat_acc_empleados; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."Dlk_cat_acc_empleados" (
    "Id" text NOT NULL,
    "Nombre" character varying(255) NOT NULL,
    "Apellidos" character varying(255) NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_empleados" OWNER TO postgres;

--
-- Name: Dlk_cat_acc_empleados_roles; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."Dlk_cat_acc_empleados_roles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_empleados_roles" OWNER TO postgres;

--
-- Name: Dlk_cat_acc_login_empleados; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."Dlk_cat_acc_login_empleados" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_login_empleados" OWNER TO postgres;

--
-- Name: Dlk_cat_acc_roles; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."Dlk_cat_acc_roles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_roles" OWNER TO postgres;

--
-- Name: Dlk_cat_acc_token_empleados; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."Dlk_cat_acc_token_empleados" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text
);


ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_token_empleados" OWNER TO postgres;

--
-- Name: tdc_cat_estados_devolucion_pedido; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol.tdc_cat_estados_devolucion_pedido (
    md_uuid character varying NOT NULL,
    md_date timestamp without time zone NOT NULL,
    id bigint NOT NULL,
    cod_estado_devolucion character varying NOT NULL,
    des_estado_devolucion character varying
);


ALTER TABLE dwh_torrecontrol.tdc_cat_estados_devolucion_pedido OWNER TO postgres;

--
-- Name: tdc_cat_estados_devolucion_pedido_id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE dwh_torrecontrol.tdc_cat_estados_devolucion_pedido ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME dwh_torrecontrol.tdc_cat_estados_devolucion_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tdc_cat_estados_envio_pedido; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol.tdc_cat_estados_envio_pedido (
    md_uuid character varying NOT NULL,
    md_date timestamp without time zone NOT NULL,
    id bigint NOT NULL,
    cod_estado_envio character varying NOT NULL,
    des_estado_envio character varying
);


ALTER TABLE dwh_torrecontrol.tdc_cat_estados_envio_pedido OWNER TO postgres;

--
-- Name: tdc_cat_estados_envio_pedido_id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE dwh_torrecontrol.tdc_cat_estados_envio_pedido ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME dwh_torrecontrol.tdc_cat_estados_envio_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tdc_cat_estados_pago_pedido; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol.tdc_cat_estados_pago_pedido (
    md_uuid character varying NOT NULL,
    md_date timestamp without time zone NOT NULL,
    id bigint NOT NULL,
    cod_estado_pago character varying NOT NULL,
    des_estado_pago character varying
);


ALTER TABLE dwh_torrecontrol.tdc_cat_estados_pago_pedido OWNER TO postgres;

--
-- Name: tdc_cat_estados_pago_pedido_id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE dwh_torrecontrol.tdc_cat_estados_pago_pedido ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME dwh_torrecontrol.tdc_cat_estados_pago_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tdc_cat_lineas_distribucion; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol.tdc_cat_lineas_distribucion (
    md_uuid character varying NOT NULL,
    md_date timestamp without time zone NOT NULL,
    id bigint NOT NULL,
    cod_linea character varying NOT NULL,
    cod_provincia character varying NOT NULL,
    cod_municipio character varying NOT NULL,
    cod_barrio character varying NOT NULL
);


ALTER TABLE dwh_torrecontrol.tdc_cat_lineas_distribucion OWNER TO postgres;

--
-- Name: tdc_cat_lineas_distribucion_id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE dwh_torrecontrol.tdc_cat_lineas_distribucion ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME dwh_torrecontrol.tdc_cat_lineas_distribucion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tdc_tch_estado_pedidos; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol.tdc_tch_estado_pedidos (
    md_uuid character varying NOT NULL,
    md_date timestamp without time zone NOT NULL,
    id bigint NOT NULL,
    cod_estado_envio character varying,
    cod_estado_pago character varying,
    cod_estado_devolucion character varying,
    cod_pedido character varying NOT NULL,
    cod_linea character varying NOT NULL
);


ALTER TABLE dwh_torrecontrol.tdc_tch_estado_pedidos OWNER TO postgres;

--
-- Name: tdc_tch_estado_pedidos_id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE dwh_torrecontrol.tdc_tch_estado_pedidos ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME dwh_torrecontrol.tdc_tch_estado_pedidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Dlk_cat_acc_claim_empleados; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

COPY dlk_torrecontrol."Dlk_cat_acc_claim_empleados" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: Dlk_cat_acc_claim_roles; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

COPY dlk_torrecontrol."Dlk_cat_acc_claim_roles" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: Dlk_cat_acc_empleados; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

COPY dlk_torrecontrol."Dlk_cat_acc_empleados" ("Id", "Nombre", "Apellidos", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
c7bfe3e8-1ac8-4aa6-a2dc-b77bc5606c36	Jesus	Patricio	jesuspatriciolozano@gmail.com	JESUSPATRICIOLOZANO@GMAIL.COM	jesuspatriciolozano@gmail.com	JESUSPATRICIOLOZANO@GMAIL.COM	f	AQAAAAEAACcQAAAAEGXTUwb+VcH3VXwFfUvuXnLY7z1rJqnrGUWyM2zzlyGFAKqwDZ2jMdj/YVVYw8oJ/w==	YHWNFVPPRROXHP65CJX5QKDMI5XK3VH2	53372a31-7a89-48ae-85d0-9830119b4086	\N	f	f	\N	t	0
45c35f0f-26b1-4136-a7a5-018b72fa42b6	Fran	Patricio	fran@gmail.com	FRAN@GMAIL.COM	fran@gmail.com	FRAN@GMAIL.COM	f	AQAAAAEAACcQAAAAEP208z8cYa+lntal2UTA1Gq2I3IqVCwp9v+FZz4WT2WWcAz9YDtp8bkPMSFWEqzjxQ==	ROSV7KVU6TTKVSL2U7WDDLBJNMMAOGVW	281e31b5-2cfd-4f7f-baf8-8fb25fb25deb	\N	f	f	\N	t	0
547e9c53-353b-47e3-be78-9520ec541b86	Macarena	Lozano	Maca@gmail.com	MACA@GMAIL.COM	Maca@gmail.com	MACA@GMAIL.COM	f	AQAAAAEAACcQAAAAEP+Di73v/dh1183LZ8/8Bq7GTvD+QzkAo2P6C3PCGx9XwpSiEZf+/xTukvC88AdTzQ==	MQEWRMJTL4DSMIQFUWIPBRGU45LKIIZW	c58fc6a1-1d82-4932-b0c4-9effa0fecb83	\N	f	f	\N	t	0
\.


--
-- Data for Name: Dlk_cat_acc_empleados_roles; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

COPY dlk_torrecontrol."Dlk_cat_acc_empleados_roles" ("UserId", "RoleId") FROM stdin;
c7bfe3e8-1ac8-4aa6-a2dc-b77bc5606c36	0
547e9c53-353b-47e3-be78-9520ec541b86	1
45c35f0f-26b1-4136-a7a5-018b72fa42b6	2
\.


--
-- Data for Name: Dlk_cat_acc_login_empleados; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

COPY dlk_torrecontrol."Dlk_cat_acc_login_empleados" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;
\.


--
-- Data for Name: Dlk_cat_acc_roles; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

COPY dlk_torrecontrol."Dlk_cat_acc_roles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
0	Administradores	Admin	\N
2	Usuarios	User	\N
1	Empleados	Empleado	\N
\.


--
-- Data for Name: Dlk_cat_acc_token_empleados; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

COPY dlk_torrecontrol."Dlk_cat_acc_token_empleados" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;
\.


--
-- Data for Name: tdc_cat_estados_devolucion_pedido; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--

COPY dwh_torrecontrol.tdc_cat_estados_devolucion_pedido (md_uuid, md_date, id, cod_estado_devolucion, des_estado_devolucion) FROM stdin;
23435	2012-12-12 11:23:00	1	2345	234fds
\.


--
-- Data for Name: tdc_cat_estados_envio_pedido; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--

COPY dwh_torrecontrol.tdc_cat_estados_envio_pedido (md_uuid, md_date, id, cod_estado_envio, des_estado_envio) FROM stdin;
\.


--
-- Data for Name: tdc_cat_estados_pago_pedido; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--

COPY dwh_torrecontrol.tdc_cat_estados_pago_pedido (md_uuid, md_date, id, cod_estado_pago, des_estado_pago) FROM stdin;
\.


--
-- Data for Name: tdc_cat_lineas_distribucion; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--

COPY dwh_torrecontrol.tdc_cat_lineas_distribucion (md_uuid, md_date, id, cod_linea, cod_provincia, cod_municipio, cod_barrio) FROM stdin;
\.


--
-- Data for Name: tdc_tch_estado_pedidos; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--

COPY dwh_torrecontrol.tdc_tch_estado_pedidos (md_uuid, md_date, id, cod_estado_envio, cod_estado_pago, cod_estado_devolucion, cod_pedido, cod_linea) FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20221206114526_dlk_torrecontrol	7.0.0
20221207175708_dlk_torrecontrol	7.0.0
\.


--
-- Name: Dlk_cat_acc_claim_empleados_Id_seq; Type: SEQUENCE SET; Schema: dlk_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dlk_torrecontrol."Dlk_cat_acc_claim_empleados_Id_seq"', 1, false);


--
-- Name: Dlk_cat_acc_claim_roles_Id_seq; Type: SEQUENCE SET; Schema: dlk_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dlk_torrecontrol."Dlk_cat_acc_claim_roles_Id_seq"', 1, false);


--
-- Name: tdc_cat_estados_devolucion_pedido_id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol.tdc_cat_estados_devolucion_pedido_id_seq', 1, true);


--
-- Name: tdc_cat_estados_envio_pedido_id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol.tdc_cat_estados_envio_pedido_id_seq', 1, false);


--
-- Name: tdc_cat_estados_pago_pedido_id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol.tdc_cat_estados_pago_pedido_id_seq', 1, false);


--
-- Name: tdc_cat_lineas_distribucion_id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol.tdc_cat_lineas_distribucion_id_seq', 1, false);


--
-- Name: tdc_tch_estado_pedidos_id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol.tdc_tch_estado_pedidos_id_seq', 1, false);


--
-- Name: Dlk_cat_acc_claim_empleados PK_Dlk_cat_acc_claim_empleados; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_claim_empleados"
    ADD CONSTRAINT "PK_Dlk_cat_acc_claim_empleados" PRIMARY KEY ("Id");


--
-- Name: Dlk_cat_acc_claim_roles PK_Dlk_cat_acc_claim_roles; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_claim_roles"
    ADD CONSTRAINT "PK_Dlk_cat_acc_claim_roles" PRIMARY KEY ("Id");


--
-- Name: Dlk_cat_acc_empleados PK_Dlk_cat_acc_empleados; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_empleados"
    ADD CONSTRAINT "PK_Dlk_cat_acc_empleados" PRIMARY KEY ("Id");


--
-- Name: Dlk_cat_acc_empleados_roles PK_Dlk_cat_acc_empleados_roles; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_empleados_roles"
    ADD CONSTRAINT "PK_Dlk_cat_acc_empleados_roles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: Dlk_cat_acc_login_empleados PK_Dlk_cat_acc_login_empleados; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_login_empleados"
    ADD CONSTRAINT "PK_Dlk_cat_acc_login_empleados" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: Dlk_cat_acc_roles PK_Dlk_cat_acc_roles; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_roles"
    ADD CONSTRAINT "PK_Dlk_cat_acc_roles" PRIMARY KEY ("Id");


--
-- Name: Dlk_cat_acc_token_empleados PK_Dlk_cat_acc_token_empleados; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_token_empleados"
    ADD CONSTRAINT "PK_Dlk_cat_acc_token_empleados" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: tdc_cat_estados_devolucion_pedido tdc_cat_estados_devolucion_pedido_pkey; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol.tdc_cat_estados_devolucion_pedido
    ADD CONSTRAINT tdc_cat_estados_devolucion_pedido_pkey PRIMARY KEY (md_uuid);


--
-- Name: tdc_cat_estados_envio_pedido tdc_cat_estados_envio_pedido_pkey; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol.tdc_cat_estados_envio_pedido
    ADD CONSTRAINT tdc_cat_estados_envio_pedido_pkey PRIMARY KEY (md_uuid);


--
-- Name: tdc_cat_estados_pago_pedido tdc_cat_estados_pago_pedido_pkey; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol.tdc_cat_estados_pago_pedido
    ADD CONSTRAINT tdc_cat_estados_pago_pedido_pkey PRIMARY KEY (md_uuid);


--
-- Name: tdc_cat_lineas_distribucion tdc_cat_lineas_distribucion_pkey; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol.tdc_cat_lineas_distribucion
    ADD CONSTRAINT tdc_cat_lineas_distribucion_pkey PRIMARY KEY (md_uuid);


--
-- Name: tdc_tch_estado_pedidos tdc_tch_estado_pedidos_pkey; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol.tdc_tch_estado_pedidos
    ADD CONSTRAINT tdc_tch_estado_pedidos_pkey PRIMARY KEY (md_uuid);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "EmailIndex" ON dlk_torrecontrol."Dlk_cat_acc_empleados" USING btree ("NormalizedEmail");


--
-- Name: IX_Dlk_cat_acc_claim_empleados_UserId; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_Dlk_cat_acc_claim_empleados_UserId" ON dlk_torrecontrol."Dlk_cat_acc_claim_empleados" USING btree ("UserId");


--
-- Name: IX_Dlk_cat_acc_claim_roles_RoleId; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_Dlk_cat_acc_claim_roles_RoleId" ON dlk_torrecontrol."Dlk_cat_acc_claim_roles" USING btree ("RoleId");


--
-- Name: IX_Dlk_cat_acc_empleados_roles_RoleId; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_Dlk_cat_acc_empleados_roles_RoleId" ON dlk_torrecontrol."Dlk_cat_acc_empleados_roles" USING btree ("RoleId");


--
-- Name: IX_Dlk_cat_acc_login_empleados_UserId; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_Dlk_cat_acc_login_empleados_UserId" ON dlk_torrecontrol."Dlk_cat_acc_login_empleados" USING btree ("UserId");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON dlk_torrecontrol."Dlk_cat_acc_roles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON dlk_torrecontrol."Dlk_cat_acc_empleados" USING btree ("NormalizedUserName");


--
-- Name: Dlk_cat_acc_claim_empleados FK_Dlk_cat_acc_claim_empleados_Dlk_cat_acc_empleados_UserId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_claim_empleados"
    ADD CONSTRAINT "FK_Dlk_cat_acc_claim_empleados_Dlk_cat_acc_empleados_UserId" FOREIGN KEY ("UserId") REFERENCES dlk_torrecontrol."Dlk_cat_acc_empleados"("Id") ON DELETE CASCADE;


--
-- Name: Dlk_cat_acc_claim_roles FK_Dlk_cat_acc_claim_roles_Dlk_cat_acc_roles_RoleId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_claim_roles"
    ADD CONSTRAINT "FK_Dlk_cat_acc_claim_roles_Dlk_cat_acc_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES dlk_torrecontrol."Dlk_cat_acc_roles"("Id") ON DELETE CASCADE;


--
-- Name: Dlk_cat_acc_empleados_roles FK_Dlk_cat_acc_empleados_roles_Dlk_cat_acc_empleados_UserId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_empleados_roles"
    ADD CONSTRAINT "FK_Dlk_cat_acc_empleados_roles_Dlk_cat_acc_empleados_UserId" FOREIGN KEY ("UserId") REFERENCES dlk_torrecontrol."Dlk_cat_acc_empleados"("Id") ON DELETE CASCADE;


--
-- Name: Dlk_cat_acc_empleados_roles FK_Dlk_cat_acc_empleados_roles_Dlk_cat_acc_roles_RoleId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_empleados_roles"
    ADD CONSTRAINT "FK_Dlk_cat_acc_empleados_roles_Dlk_cat_acc_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES dlk_torrecontrol."Dlk_cat_acc_roles"("Id") ON DELETE CASCADE;


--
-- Name: Dlk_cat_acc_login_empleados FK_Dlk_cat_acc_login_empleados_Dlk_cat_acc_empleados_UserId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_login_empleados"
    ADD CONSTRAINT "FK_Dlk_cat_acc_login_empleados_Dlk_cat_acc_empleados_UserId" FOREIGN KEY ("UserId") REFERENCES dlk_torrecontrol."Dlk_cat_acc_empleados"("Id") ON DELETE CASCADE;


--
-- Name: Dlk_cat_acc_token_empleados FK_Dlk_cat_acc_token_empleados_Dlk_cat_acc_empleados_UserId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_token_empleados"
    ADD CONSTRAINT "FK_Dlk_cat_acc_token_empleados_Dlk_cat_acc_empleados_UserId" FOREIGN KEY ("UserId") REFERENCES dlk_torrecontrol."Dlk_cat_acc_empleados"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

