--
-- PostgreSQL database dump
--

-- Dumped from database version 15.0
-- Dumped by pg_dump version 15.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: dlk_informacional; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA dlk_informacional;


ALTER SCHEMA dlk_informacional OWNER TO postgres;

--
-- Name: dlk_torrecontrol; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA dlk_torrecontrol;


ALTER SCHEMA dlk_torrecontrol OWNER TO postgres;

--
-- Name: dmt_torrecontrol; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA dmt_torrecontrol;


ALTER SCHEMA dmt_torrecontrol OWNER TO postgres;

--
-- Name: dwh_torrecontrol; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA dwh_torrecontrol;


ALTER SCHEMA dwh_torrecontrol OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE dlk_torrecontrol."AspNetRoleClaims" OWNER TO postgres;

--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE dlk_torrecontrol."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dlk_torrecontrol."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


ALTER TABLE dlk_torrecontrol."AspNetRoles" OWNER TO postgres;

--
-- Name: AspNetUserClaims; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


ALTER TABLE dlk_torrecontrol."AspNetUserClaims" OWNER TO postgres;

--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE dlk_torrecontrol."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME dlk_torrecontrol."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."AspNetUserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


ALTER TABLE dlk_torrecontrol."AspNetUserLogins" OWNER TO postgres;

--
-- Name: AspNetUserRoles; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


ALTER TABLE dlk_torrecontrol."AspNetUserRoles" OWNER TO postgres;

--
-- Name: AspNetUserTokens; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text
);


ALTER TABLE dlk_torrecontrol."AspNetUserTokens" OWNER TO postgres;

--
-- Name: AspNetUsers; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."AspNetUsers" (
    "Id" text NOT NULL,
    "Nombre" character varying(255) NOT NULL,
    "Apellidos" character varying(255) NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE dlk_torrecontrol."AspNetUsers" OWNER TO postgres;

--
-- Name: Dlk_cat_acc_empleados; Type: TABLE; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE TABLE dlk_torrecontrol."Dlk_cat_acc_empleados" (
    "Id" text NOT NULL,
    "UserName" text,
    "NormalizedUserName" text,
    "Email" text,
    "NormalizedEmail" text,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


ALTER TABLE dlk_torrecontrol."Dlk_cat_acc_empleados" OWNER TO postgres;

--
-- Name: tdc_cat_estados_devolucion_pedido; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol.tdc_cat_estados_devolucion_pedido (
    md_uuid character varying NOT NULL,
    md_date timestamp without time zone NOT NULL,
    id bigint NOT NULL,
    cod_estado_devolucion character varying NOT NULL,
    des_estado_devolucion character varying
);


ALTER TABLE dwh_torrecontrol.tdc_cat_estados_devolucion_pedido OWNER TO postgres;

--
-- Name: tdc_cat_estados_devolucion_pedido_id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE dwh_torrecontrol.tdc_cat_estados_devolucion_pedido ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME dwh_torrecontrol.tdc_cat_estados_devolucion_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tdc_cat_estados_envio_pedido; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol.tdc_cat_estados_envio_pedido (
    md_uuid character varying NOT NULL,
    md_date timestamp without time zone NOT NULL,
    id bigint NOT NULL,
    cod_estado_envio character varying NOT NULL,
    des_estado_envio character varying
);


ALTER TABLE dwh_torrecontrol.tdc_cat_estados_envio_pedido OWNER TO postgres;

--
-- Name: tdc_cat_estados_envio_pedido_id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE dwh_torrecontrol.tdc_cat_estados_envio_pedido ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME dwh_torrecontrol.tdc_cat_estados_envio_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tdc_cat_estados_pago_pedido; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol.tdc_cat_estados_pago_pedido (
    md_uuid character varying NOT NULL,
    md_date timestamp without time zone NOT NULL,
    id bigint NOT NULL,
    cod_estado_pago character varying NOT NULL,
    des_estado_pago character varying
);


ALTER TABLE dwh_torrecontrol.tdc_cat_estados_pago_pedido OWNER TO postgres;

--
-- Name: tdc_cat_estados_pago_pedido_id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE dwh_torrecontrol.tdc_cat_estados_pago_pedido ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME dwh_torrecontrol.tdc_cat_estados_pago_pedido_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tdc_cat_lineas_distribucion; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol.tdc_cat_lineas_distribucion (
    md_uuid character varying NOT NULL,
    md_date timestamp without time zone NOT NULL,
    id bigint NOT NULL,
    cod_linea character varying NOT NULL,
    cod_provincia character varying NOT NULL,
    cod_municipio character varying NOT NULL,
    cod_barrio character varying NOT NULL
);


ALTER TABLE dwh_torrecontrol.tdc_cat_lineas_distribucion OWNER TO postgres;

--
-- Name: tdc_cat_lineas_distribucion_id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE dwh_torrecontrol.tdc_cat_lineas_distribucion ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME dwh_torrecontrol.tdc_cat_lineas_distribucion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tdc_tch_estado_pedidos; Type: TABLE; Schema: dwh_torrecontrol; Owner: postgres
--

CREATE TABLE dwh_torrecontrol.tdc_tch_estado_pedidos (
    md_uuid character varying NOT NULL,
    md_date timestamp without time zone NOT NULL,
    id bigint NOT NULL,
    cod_estado_envio character varying,
    cod_estado_pago character varying,
    cod_estado_devolucion character varying,
    cod_pedido character varying NOT NULL,
    cod_linea character varying NOT NULL
);


ALTER TABLE dwh_torrecontrol.tdc_tch_estado_pedidos OWNER TO postgres;

--
-- Name: tdc_tch_estado_pedidos_id_seq; Type: SEQUENCE; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE dwh_torrecontrol.tdc_tch_estado_pedidos ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME dwh_torrecontrol.tdc_tch_estado_pedidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

COPY dlk_torrecontrol."AspNetRoleClaims" ("Id", "RoleId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

COPY dlk_torrecontrol."AspNetRoles" ("Id", "Name", "NormalizedName", "ConcurrencyStamp") FROM stdin;
1	Administradores	Admin	\N
2	Usuarios	User	\N
3	Empleados	Empleado	\N
\.


--
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

COPY dlk_torrecontrol."AspNetUserClaims" ("Id", "UserId", "ClaimType", "ClaimValue") FROM stdin;
\.


--
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

COPY dlk_torrecontrol."AspNetUserLogins" ("LoginProvider", "ProviderKey", "ProviderDisplayName", "UserId") FROM stdin;
\.


--
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

COPY dlk_torrecontrol."AspNetUserRoles" ("UserId", "RoleId") FROM stdin;
9059298c-d66e-499b-962b-ff8fcae7f9ec	1
bf162eef-12c3-4735-ac0b-9eef3a03b319	2
d23fda78-deba-41aa-98a9-c16866fd7fdd	3
\.


--
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

COPY dlk_torrecontrol."AspNetUserTokens" ("UserId", "LoginProvider", "Name", "Value") FROM stdin;
\.


--
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

COPY dlk_torrecontrol."AspNetUsers" ("Id", "Nombre", "Apellidos", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
9059298c-d66e-499b-962b-ff8fcae7f9ec	jesus	patricio	jesuspatriciolozano@gmail.com	JESUSPATRICIOLOZANO@GMAIL.COM	jesuspatriciolozano@gmail.com	JESUSPATRICIOLOZANO@GMAIL.COM	t	AQAAAAEAACcQAAAAEA2v0ZOz4SK+ZrDtQ7o4ASr+uksXGotQfUOTh7JREqrBgxAtIt3B7Dm80XQcfLb0BQ==	6CDOFKBN5E6ZS25Z3Y2KUTKXKMDBIVRW	08f4a907-8a7d-4057-ad2c-c23077b63b4d	\N	f	f	\N	t	0
d23fda78-deba-41aa-98a9-c16866fd7fdd	Fran	Patricio	fran@gmail.com	FRAN@GMAIL.COM	fran@gmail.com	FRAN@GMAIL.COM	f	AQAAAAEAACcQAAAAEArKZdRMERdwRoJUhHaTzwb6b2UEYf6Gxfvbp5VBWgdW0Oo8yCSoSt+HIW1pXQuNgA==	Y6B2C2FJHLAYPX4SPCFU2DYQYEQCVSOV	41270ee0-9dbf-4fc9-a1dd-1c53985b9099	\N	f	f	\N	t	0
bf162eef-12c3-4735-ac0b-9eef3a03b319	Macarena	Lozano	macarena@gmail.com	MACARENA@GMAIL.COM	macarena@gmail.com	MACARENA@GMAIL.COM	f	AQAAAAEAACcQAAAAEFWjZs+l2JNlkhhZL/Pw3I+pT2uqLVDeBTh8tCrsxi359wC6afo6uVs6BSJ6+gMqGQ==	BLNC2S7P45KXYZO3BV4OALRO5JVYN2K3	cd0cb9a3-918b-42ab-918f-93f4379378df	\N	f	f	\N	t	0
\.


--
-- Data for Name: Dlk_cat_acc_empleados; Type: TABLE DATA; Schema: dlk_torrecontrol; Owner: postgres
--

COPY dlk_torrecontrol."Dlk_cat_acc_empleados" ("Id", "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed", "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumber", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnd", "LockoutEnabled", "AccessFailedCount") FROM stdin;
\.


--
-- Data for Name: tdc_cat_estados_devolucion_pedido; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--

COPY dwh_torrecontrol.tdc_cat_estados_devolucion_pedido (md_uuid, md_date, id, cod_estado_devolucion, des_estado_devolucion) FROM stdin;
23435	2012-12-12 11:23:00	1	2345	234fds
\.


--
-- Data for Name: tdc_cat_estados_envio_pedido; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--

COPY dwh_torrecontrol.tdc_cat_estados_envio_pedido (md_uuid, md_date, id, cod_estado_envio, des_estado_envio) FROM stdin;
\.


--
-- Data for Name: tdc_cat_estados_pago_pedido; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--

COPY dwh_torrecontrol.tdc_cat_estados_pago_pedido (md_uuid, md_date, id, cod_estado_pago, des_estado_pago) FROM stdin;
\.


--
-- Data for Name: tdc_cat_lineas_distribucion; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--

COPY dwh_torrecontrol.tdc_cat_lineas_distribucion (md_uuid, md_date, id, cod_linea, cod_provincia, cod_municipio, cod_barrio) FROM stdin;
\.


--
-- Data for Name: tdc_tch_estado_pedidos; Type: TABLE DATA; Schema: dwh_torrecontrol; Owner: postgres
--

COPY dwh_torrecontrol.tdc_tch_estado_pedidos (md_uuid, md_date, id, cod_estado_envio, cod_estado_pago, cod_estado_devolucion, cod_pedido, cod_linea) FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20221206114526_dlk_torrecontrol	7.0.0
\.


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: dlk_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dlk_torrecontrol."AspNetRoleClaims_Id_seq"', 1, false);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: dlk_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dlk_torrecontrol."AspNetUserClaims_Id_seq"', 1, false);


--
-- Name: tdc_cat_estados_devolucion_pedido_id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol.tdc_cat_estados_devolucion_pedido_id_seq', 1, true);


--
-- Name: tdc_cat_estados_envio_pedido_id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol.tdc_cat_estados_envio_pedido_id_seq', 1, false);


--
-- Name: tdc_cat_estados_pago_pedido_id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol.tdc_cat_estados_pago_pedido_id_seq', 1, false);


--
-- Name: tdc_cat_lineas_distribucion_id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol.tdc_cat_lineas_distribucion_id_seq', 1, false);


--
-- Name: tdc_tch_estado_pedidos_id_seq; Type: SEQUENCE SET; Schema: dwh_torrecontrol; Owner: postgres
--

SELECT pg_catalog.setval('dwh_torrecontrol.tdc_tch_estado_pedidos_id_seq', 1, false);


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: Dlk_cat_acc_empleados PK_Dlk_cat_acc_empleados; Type: CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."Dlk_cat_acc_empleados"
    ADD CONSTRAINT "PK_Dlk_cat_acc_empleados" PRIMARY KEY ("Id");


--
-- Name: tdc_cat_estados_devolucion_pedido tdc_cat_estados_devolucion_pedido_pkey; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol.tdc_cat_estados_devolucion_pedido
    ADD CONSTRAINT tdc_cat_estados_devolucion_pedido_pkey PRIMARY KEY (md_uuid);


--
-- Name: tdc_cat_estados_envio_pedido tdc_cat_estados_envio_pedido_pkey; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol.tdc_cat_estados_envio_pedido
    ADD CONSTRAINT tdc_cat_estados_envio_pedido_pkey PRIMARY KEY (md_uuid);


--
-- Name: tdc_cat_estados_pago_pedido tdc_cat_estados_pago_pedido_pkey; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol.tdc_cat_estados_pago_pedido
    ADD CONSTRAINT tdc_cat_estados_pago_pedido_pkey PRIMARY KEY (md_uuid);


--
-- Name: tdc_cat_lineas_distribucion tdc_cat_lineas_distribucion_pkey; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol.tdc_cat_lineas_distribucion
    ADD CONSTRAINT tdc_cat_lineas_distribucion_pkey PRIMARY KEY (md_uuid);


--
-- Name: tdc_tch_estado_pedidos tdc_tch_estado_pedidos_pkey; Type: CONSTRAINT; Schema: dwh_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dwh_torrecontrol.tdc_tch_estado_pedidos
    ADD CONSTRAINT tdc_tch_estado_pedidos_pkey PRIMARY KEY (md_uuid);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "EmailIndex" ON dlk_torrecontrol."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON dlk_torrecontrol."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON dlk_torrecontrol."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON dlk_torrecontrol."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON dlk_torrecontrol."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE UNIQUE INDEX "RoleNameIndex" ON dlk_torrecontrol."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: dlk_torrecontrol; Owner: postgres
--

CREATE UNIQUE INDEX "UserNameIndex" ON dlk_torrecontrol."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES dlk_torrecontrol."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES dlk_torrecontrol."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES dlk_torrecontrol."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES dlk_torrecontrol."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES dlk_torrecontrol."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: dlk_torrecontrol; Owner: postgres
--

ALTER TABLE ONLY dlk_torrecontrol."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES dlk_torrecontrol."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

